import type { Metadata } from "next";
import "./globals.css";
import { Poiret_One, Montserrat } from 'next/font/google';
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

//El layout encierra a todas las pages
//Poiret One
const primaryFont = Poiret_One({
  subsets: ['latin'],
  variable: '--font-primary',
  weight:['400'],
});

//Montserrat
const secondaryFont = Montserrat({
  subsets: ['latin'],
  variable: '--font-secondary',
  weight: ['400'], // Especifica los pesos que necesitas
});

export const metadata: Metadata = {
  title: "E-commerce Project M4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}
      >
        <Navbar/>
        <main className="container">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
