import type { Metadata } from "next";
import "./globals.css";
import { Poiret_One, Montserrat } from 'next/font/google';
import { NextUIProvider } from "@nextui-org/react"; // Importa el proveedor de NextUI
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthProvider } from "../../context/authContext";


const primaryFont = Poiret_One({
  subsets: ['latin'],
  variable: '--font-primary',
  weight: ['400'],
});

const secondaryFont = Montserrat({
  subsets: ['latin'],
  variable: '--font-secondary',
  weight: ['400'], 
});

export const metadata: Metadata = {
  title: "E-commerce Project M4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}
      >
          <Navbar />
          <main className="container">
            {children}
          </main>
          <Footer />
          </body>
    </html>
    </AuthProvider>
  );
}
